openapi: 3.0.1
info:
  title: testapi
  description: ''
  version: '1.0'
servers:
  - url: https://api.waelsconsulting.com/test
  - url: https://portal.waelsconsulting.com/test
paths:
  /earth:
    get:
      summary: Earth Search
      description: returns search of earth v2
      operationId: earth-search
      responses:
        '200':
          description: ''
  /sun:
    get:
      summary: Sun Search
      description: return results of the sun
      operationId: sun-search
      responses:
        '200':
          description: ''
  /getstuff:
    get:
      summary: getstuff
      description: getstuff
      operationId: getstuff
      responses:
        '200':
          description: ''
    post:
      summary: getStuff
      operationId: get-stuff
      responses:
        '200':
          description: ''
  /test:
    get:
      description: 'test'
      parameters: []
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]