trigger:
  paths:
    include:
      - code/common
      - code/extractor

variables:
  - group: apim-automation
  - name: System.Debug
    value: true

stages:
  - stage: publish_extractor
    displayName: Publish extractor
    jobs:
      - job: publish_extractor
        displayName: Publish extractor
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UseDotNet@2
            displayName: Install .NET Core SDK
            inputs:
              version: 6.x
              includePreviewVersions: true
          - task: DotNetCoreCLI@2
            displayName: Publish .NET Core application
            inputs:
              command: publish
              publishWebProjects: false
              projects: '$(Build.SourcesDirectory)/code/extractor/extractor.csproj'
              arguments: '--output $(Build.ArtifactStagingDirectory) --runtime linux-x64 -p:PublishSingleFile=true'
              modifyOutputPath: false
              zipAfterPublish: false
          - task: UniversalPackages@0
            displayName: Publish extractor artifact
            inputs:
              command: publish
              vstsFeedPublish: $(System.TeamProject)/$(ARTIFACTS_FEED_NAME)
              vstsFeedPackagePublish: extractor
              packagePublishDescription: 'APIM extractor tool'