trigger: none

resources:
  repositories:
    - repository: apim-artifacts
      type: git
      name: apim-artifacts
      trigger:
        branches:
          include:
            - main

variables:
  - group: apim-automation
  - name: System.Debug
    value: true

stages:
  - stage: push_changes_to_azure
    displayName: Push changes to Azure
    jobs:
      - job: push_changes_to_azure
        displayName: Push changes to Azure
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
          - checkout: apim-artifacts
          - task: UniversalPackages@0
            displayName: Download creator
            inputs:
              downloadDirectory: '$(Pipeline.Workspace)/creator'
              vstsFeed: $(System.TeamProject)/$(ARTIFACTS_FEED_NAME)
              vstsFeedPackage: 'creator'
              vstsPackageVersion: '*'
          - task: AzureCLI@2
            displayName: Set creation variables
            inputs:
              azureSubscription: "$(SERVICE_CONNECTION_NAME)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "##vso[task.setvariable issecret=true;variable=AZURE_BEARER_TOKEN]$(az account get-access-token --query "accessToken" --output tsv)"
                echo "##vso[task.setvariable issecret=true;variable=AZURE_CLIENT_ID]$servicePrincipalId"
                echo "##vso[task.setvariable issecret=true;variable=AZURE_CLIENT_SECRET]$servicePrincipalKey"
                echo "##vso[task.setvariable issecret=true;variable=AZURE_TENANT_ID]$tenantId"
                echo "##vso[task.setvariable issecret=true;variable=AZURE_SUBSCRIPTION_ID]$(az account show --query "id" --output tsv)"
              addSpnToEnvironment: true
              failOnStandardError: true
          - task: AzureCLI@2
            displayName: Run creator
            inputs:
              azureSubscription: "$(SERVICE_CONNECTION_NAME)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                chmod u+x $(Pipeline.Workspace)/creator/creator
                $(Pipeline.Workspace)/creator/creator
                echo "Exit code is $?"
                exit $?
              addSpnToEnvironment: true
              failOnStandardError: true
            env:
              AZURE_BEARER_TOKEN: $(AZURE_BEARER_TOKEN)
              AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
              AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
              AZURE_TENANT_ID: $(AZURE_TENANT_ID)
              AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              AZURE_RESOURCE_GROUP_NAME: $(RESOURCE_GROUP_NAME)
              API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: $(Build.SourcesDirectory)/$(Build.Repository.Name)
              COMMIT_ID: $(Build.SourceVersion)