openapi: 3.0.1
info:
  title: myversionedapi
  description: ''
  version: v2
servers:
  - url: https://apim-wk-05102022.azure-api.net/myversionedapi/v2
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]